return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "2020.06.12",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 256,
  height = 256,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 15,
  nextobjectid = 957,
  properties = {},
  tilesets = {
    {
      name = "color_32",
      firstgid = 1,
      filename = "color_32.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "colors_32.png",
      imagewidth = 128,
      imageheight = 128,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 16,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 256,
      height = 256,
      id = 10,
      name = "x_level",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt3c1y2yAUBlBv3GnaRd7/bbuM6xGIy69kzuLMtI4kuMCHiLvo9+Px+K7wLPzsKp5vej1zdV3Qy3tGcl7vOfpz7pk9+hFt472fZ305u6bnPpKqI3ddybOi98CR0rXYa81F7svtBzWflfy89zniqK2afuXGcESfS59dclas3e8i74kR9UbbacnE6Lpqx79mTktqbelbadajZ4DXv7fOw/PgmWd9qz0jlO4trfVEz4/RNRZdX6P2u0gbrXtT9L01ut7SddXSx5n5P3tGat565r+0tsgZIVfnrPXTOo/R8VlRTyT/qfkYMaYz5jC3r7WcWSLvuZL9NfIuOqo79cwe45pb32fr5uzeXH9nrKNPy39rP87OfL3bG13fHd//pXtS689L+l4iVUdkblLXjl5L8p+e95Y1c5X67pL/VP9q1l2P+lraiJwBos+auXZKr/vE/M9qa3R9V8x/ak1H1/+d8t+y343cAyLzGDkHje537/p69PkK9db092weW9dN6b25z2vOxlfJf+k4tOx1o+orue6sz7VrbFZtvcb5TtmfpUf+o8/pOR+98n90ba+xGVnfqLmZQf5pVbvHlL4Te/VjVH0l110x/7XnjF3O/ox19rtMNPvyH69rdv5X1svnmfH78qfmf/R4fEq9XMeK78lK2+mR/9nf/62Yu9X9gBFq8r/qe/8rjhHc2Yp/mwQAqOFsAsxgrwGAe/IOBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4E5+AQAAAAAA2/oCbkH+YV/yD/uSf9iX/MO+5B/2Jf+wL/mHfck/7Ev+YV/yD/uSf9jX6Pz/frG6VuB/q/P/Z7BU3aPbzbWdGp8VVq8/1ork+i8AAAAAAAAAAHBbq///UQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgxz/NSDx6"
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "game_screen",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 432,
          name = "",
          type = "",
          shape = "polygon",
          x = 640,
          y = 3168,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 416, y = 0 },
            { x = 416, y = -192 },
            { x = -416, y = -192 },
            { x = -416, y = 192 },
            { x = 416, y = 192 },
            { x = 416, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "fg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "sensors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 0, 0, 0 },
      properties = {},
      objects = {
        {
          id = 581,
          name = "exit",
          type = "",
          shape = "rectangle",
          x = 4544,
          y = 2848,
          width = 32,
          height = 448,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 949,
          name = "cam_zoomX05",
          type = "",
          shape = "rectangle",
          x = 4352,
          y = 3168,
          width = 96,
          height = 416,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 952,
          name = "cam_zoomX1",
          type = "",
          shape = "rectangle",
          x = 4000,
          y = 3168,
          width = 96,
          height = 416,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 954,
          name = "cam_pos",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 3232,
          width = 224,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 955,
          name = "cam_pos",
          type = "",
          shape = "rectangle",
          x = 4256,
          y = 3168,
          width = 288,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 956,
          name = "cam_pos",
          type = "",
          shape = "rectangle",
          x = 3424,
          y = 3232,
          width = 320,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "mg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 950,
          name = "ground02",
          type = "",
          shape = "polygon",
          x = 4000,
          y = 3299.33,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = -8.66667 },
            { x = 96, y = -17.3333 },
            { x = 192, y = -26 },
            { x = 320, y = -34.6667 },
            { x = 480, y = -43.3333 },
            { x = 576, y = -43.3333 },
            { x = 576, y = 60.6667 },
            { x = 0, y = 60.6667 }
          },
          properties = {}
        },
        {
          id = 589,
          name = "player",
          type = "",
          shape = "polygon",
          x = 448,
          y = 3168,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 48, y = 0 },
            { x = 48, y = 32 },
            { x = -48, y = 32 },
            { x = -48, y = -32 },
            { x = 48, y = -32 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 574,
          name = "ground01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 3296,
          width = 4576,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 2656,
          width = 320,
          height = 928,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "ceiling01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 2656,
          width = 4576,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 575,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 4576,
          y = 2656,
          width = 352,
          height = 928,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "bg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 684,
          name = "tex01",
          type = "",
          shape = "polygon",
          x = 544,
          y = 3296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -32 },
            { x = -8, y = -32 },
            { x = -8, y = -40 },
            { x = 80, y = -40 },
            { x = 80, y = -32 },
            { x = 72, y = -32 },
            { x = 72, y = 0 },
            { x = 64, y = 0 },
            { x = 64, y = -32 },
            { x = 8, y = -32 },
            { x = 8, y = 0 }
          },
          properties = {}
        },
        {
          id = 943,
          name = "tex02",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 3264,
          width = 768,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 944,
          name = "tex02",
          type = "",
          shape = "rectangle",
          x = 1632,
          y = 3264,
          width = 800,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 945,
          name = "tex03",
          type = "",
          shape = "rectangle",
          x = 2720,
          y = 3264,
          width = 1024,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
