return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "2020.06.12",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 256,
  height = 256,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 16,
  nextobjectid = 439,
  properties = {},
  tilesets = {
    {
      name = "color_32",
      firstgid = 1,
      filename = "color_32.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "colors_32.png",
      imagewidth = 128,
      imageheight = 128,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 16,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 256,
      height = 256,
      id = 11,
      name = "x_deco",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2EFOw0AMBdDsirrh/rdFLCpVUTSxPZ42hfekSCCI/8fJsOi2AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD/cn+6jr7PuBXyKiI5mbzRvErf1TvsyM52rPQ6yliZO7P36L2v6tM5YzTz7Ir63cvXdryfjvmRnEre0bxK39U7HIlmVztmemXerY7cmb1n713dp3NGZXY177GXxxU9S9m/Z5RTyTuaV+m7eocj0exqx0yv7Ls1mzuz9+y9q/t0zpjNyOQ972X/dSQvKpKTyRvNq/RdvcORaHa2Y6VXx/nvftaVru/o0zmjOj+btf+/mDn/GZGcTN5oXqXv6h12ZGc7VnrNnv1s7szeo/e+qk/njIh9/8pnPJndzHy2VXkXz352Nq+6j8o9M+c/m535vWqvmeff/awjeVfq0zkjM9/5d/67ejn/81af/w63wXXlnFf1/rQuz97V62r7uFqfv+D75OIzeG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ8wNpaBqy"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 256,
      height = 256,
      id = 10,
      name = "x_level",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt2NtuhCAQAFDa1P//5b60qSECM6jVXc9JSDYut12dASzlz/JTIpaSq79ut6d9by7AnKXEY3IJfJ5tl8kLdV15AOZsxWCv7laczsZ/a9zIPCLXRnO6U86401x4jvq5i8Z/r59en5H4j8wjcq3Xfr13yLTL9J1x9LkIRur1fHb9LyUW/62xZuJ/z/uEzFjZepl90brO6CwzmnMkx0Jtb9yN+on0n81DdZus7Fh12+j30d++nlP9uVTXomew2RzHs2TXitYzd2T8R0T2Ib22dT9RkRiN1t+aS6SvSH17ACKOeiYy8T+6Fl3/13Uz+WPP2rh1dun1MzqnZGLYGYBX0YvH6H6/9by28kVm79DrL9K+tW/vjTXKGaM8mMkP4p+rzeyr62uRmBrtsWfHz7Sd2d9vjbtnjRf/PEFv33DFM97LO6NcFT3ntPqLfJfdHwHniL7nmHmX0Yr51llFToBrtd5FzL7LiNQX9/AexDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDxvlYFuI+PRjmS+Id7+o/4P8vnqrySPf/zq92jX3eY99VzuHr8LeK/lGVQjib+zzG6b1f/d1ePv+Ws+B/F1J3KO/2WJxf37T4FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgHv6BmExC+E="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "game_screen",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 251,
          name = "",
          type = "",
          shape = "polygon",
          x = 544,
          y = 1344,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 416, y = 0 },
            { x = 416, y = -224 },
            { x = -416, y = -224 },
            { x = -416, y = 224 },
            { x = 416, y = 224 },
            { x = 416, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "fg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 432,
          name = "",
          type = "",
          shape = "polygon",
          x = 1440,
          y = 1496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 64, y = -8 },
            { x = 128, y = 0 },
            { x = 128, y = 8 },
            { x = 0, y = 8 }
          },
          properties = {}
        },
        {
          id = 433,
          name = "",
          type = "",
          shape = "polygon",
          x = 5056,
          y = 1496,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = -8 },
            { x = 64, y = 0 },
            { x = 64, y = 8 },
            { x = 0, y = 8 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "sensors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      tintcolor = { 0, 0, 0 },
      properties = {},
      objects = {
        {
          id = 340,
          name = "exit",
          type = "",
          shape = "rectangle",
          x = 8160,
          y = 992,
          width = 32,
          height = 544,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "cam_pos",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 1472,
          width = 192,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "mg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 95,
          name = "player",
          type = "",
          shape = "polygon",
          x = 192,
          y = 1408,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 48, y = 0 },
            { x = 48, y = 32 },
            { x = -48, y = 32 },
            { x = -48, y = -32 },
            { x = 48, y = -32 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 7,
          name = "ceiling01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 928,
          width = 8192,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = -256,
          y = 928,
          width = 256,
          height = 640,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 8192,
          y = 928,
          width = 352,
          height = 640,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 4224,
          y = 1376,
          width = 112,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 2272,
          y = 1376,
          width = 112,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 2752,
          y = 1376,
          width = 112,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 1792,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 271,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 1824,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 272,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 1856,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 273,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 1888,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 274,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 1920,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 275,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 1952,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 331,
          name = "ground01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1536,
          width = 1376,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "ground02",
          type = "",
          shape = "rectangle",
          x = 1632,
          y = 1536,
          width = 3392,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "ground01",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 1536,
          width = 3040,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "npc01",
          type = "",
          shape = "polygon",
          x = 848,
          y = 1440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 48, y = 0 },
            { x = 48, y = 32 },
            { x = -48, y = 32 },
            { x = -48, y = -32 },
            { x = 48, y = -32 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 337,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 5248,
          y = 1376,
          width = 112,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 338,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 6272,
          y = 1376,
          width = 112,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 339,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 7520,
          y = 1440,
          width = 112,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 342,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 3584,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 343,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 3552,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 344,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 3616,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 345,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 3648,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 346,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 3680,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 347,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 3712,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 348,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 5728,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 349,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 5760,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 350,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 5792,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 351,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 5824,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 352,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 5856,
          y = 1472,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 353,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 5888,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 417,
          name = "coin",
          type = "",
          shape = "polygon",
          x = 1760,
          y = 1504,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 32, y = 0 },
            { x = 0, y = -32 },
            { x = -32, y = 0 },
            { x = 0, y = 32 },
            { x = 32, y = 0 }
          },
          properties = {}
        },
        {
          id = 420,
          name = "ground03",
          type = "",
          shape = "polygon",
          x = 1312,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 128, y = -32 },
            { x = 256, y = -32 },
            { x = 384, y = 0 }
          },
          properties = {}
        },
        {
          id = 421,
          name = "ground03",
          type = "",
          shape = "polygon",
          x = 4960,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 96, y = -32 },
            { x = 160, y = -32 },
            { x = 256, y = 0 }
          },
          properties = {}
        },
        {
          id = 434,
          name = "mpf_h_r_6",
          type = "",
          shape = "rectangle",
          x = 385,
          y = 1472,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "mpf_v_u_4",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1488,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "mpf_h_l_6",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 1408,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "mpf_v_d_4",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1312,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "bg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 325,
          name = "tex01",
          type = "",
          shape = "polygon",
          x = -255.575,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = -0.425001, y = 192.001 },
            { x = 1631.57, y = 192.001 },
            { x = 1631.57, y = 384 },
            { x = 0, y = 384 }
          },
          properties = {}
        },
        {
          id = 355,
          name = "tex01",
          type = "",
          shape = "rectangle",
          x = 1632,
          y = 1568,
          width = 3392,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 356,
          name = "river",
          type = "",
          shape = "rectangle",
          x = 1376,
          y = 1568,
          width = 256,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 359,
          name = "river",
          type = "",
          shape = "rectangle",
          x = 5024,
          y = 1568,
          width = 128,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 360,
          name = "tex01",
          type = "",
          shape = "rectangle",
          x = 5152,
          y = 1568,
          width = 3392,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 384,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 362,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 319.639,
          y = 1356.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 393.624,
          y = 1297.21,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 304.842,
          y = 1252.82,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 512,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 366,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 430.797,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 504.782,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 368,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 416,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 369,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 1280,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 370,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 1198.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 371,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 1272.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 372,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 1184,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 373,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 2176,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 374,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 2094.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 375,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 2168.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 2080,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 377,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 2656,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 378,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 2606.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 379,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 2680.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 380,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 2592,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 381,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 3104,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 382,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 3022.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 383,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 3096.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 384,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 3008,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 4064,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 386,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 4014.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 4088.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 4000,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 4416,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 390,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 4334.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 4408.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 392,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 4320,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 5216,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 394,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 5134.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 5208.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 5120,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 5344,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 398,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 5294.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 5368.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 5280,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 6080,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 402,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 6030.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 6104.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 6016,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 6592,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 406,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 6510.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 6584.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 6496,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 7264,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 410,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 7182.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 7256.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 7168,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "tex02",
          type = "",
          shape = "polygon",
          x = 7776,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.7971, y = -59.1882 },
            { x = 14.7971, y = -118.376 },
            { x = 44.3911, y = -118.376 },
            { x = 59.1882, y = -59.1882 },
            { x = 44.3911, y = 0 }
          },
          properties = {}
        },
        {
          id = 414,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 7726.8,
          y = 1351.58,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 7800.78,
          y = 1292.39,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "tex03",
          type = "",
          shape = "ellipse",
          x = 7712,
          y = 1248,
          width = 118.376,
          height = 103.579,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "tex04",
          type = "",
          shape = "polygon",
          x = 1760,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -172.8 },
            { x = 112, y = -288 },
            { x = 224, y = -172.8 },
            { x = 224, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 419,
          name = "tex04",
          type = "",
          shape = "polygon",
          x = 928,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -172.8 },
            { x = 112, y = -288 },
            { x = 224, y = -172.8 },
            { x = 224, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 423,
          name = "tex04",
          type = "",
          shape = "polygon",
          x = 2400,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -172.8 },
            { x = 112, y = -288 },
            { x = 224, y = -172.8 },
            { x = 224, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 425,
          name = "tex04",
          type = "",
          shape = "polygon",
          x = 3532.44,
          y = 1536,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -153.6 },
            { x = 99.5556, y = -256 },
            { x = 199.111, y = -153.6 },
            { x = 199.111, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 427,
          name = "tex04",
          type = "",
          shape = "polygon",
          x = 4736,
          y = 1552,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -172.8 },
            { x = 112, y = -288 },
            { x = 224, y = -172.8 },
            { x = 224, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 429,
          name = "tex04",
          type = "",
          shape = "polygon",
          x = 5696,
          y = 1552,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -172.8 },
            { x = 112, y = -288 },
            { x = 224, y = -172.8 },
            { x = 224, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 431,
          name = "tex04",
          type = "",
          shape = "polygon",
          x = 6848,
          y = 1552,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -172.8 },
            { x = 112, y = -288 },
            { x = 224, y = -172.8 },
            { x = 224, y = 0 },
            { x = 0, y = 0 }
          },
          properties = {}
        },
        {
          id = 330,
          name = "windmill",
          type = "",
          shape = "polygon",
          x = 1872,
          y = 1360,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 0 },
            { x = 16, y = -16 },
            { x = -16, y = -16 },
            { x = -16, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 357,
          name = "windmill",
          type = "",
          shape = "polygon",
          x = 1040,
          y = 1360,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 0 },
            { x = 16, y = -16 },
            { x = -16, y = -16 },
            { x = -16, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 422,
          name = "windmill",
          type = "",
          shape = "polygon",
          x = 2512,
          y = 1360,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 0 },
            { x = 16, y = -16 },
            { x = -16, y = -16 },
            { x = -16, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 424,
          name = "windmill",
          type = "",
          shape = "polygon",
          x = 3632,
          y = 1379.56,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.2222, y = 0 },
            { x = 14.2222, y = -14.2222 },
            { x = -14.2222, y = -14.2222 },
            { x = -14.2222, y = 14.2222 },
            { x = 14.2222, y = 14.2222 },
            { x = 14.2222, y = 0 }
          },
          properties = {}
        },
        {
          id = 426,
          name = "windmill",
          type = "",
          shape = "polygon",
          x = 4848,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 0 },
            { x = 16, y = -16 },
            { x = -16, y = -16 },
            { x = -16, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 428,
          name = "windmill",
          type = "",
          shape = "polygon",
          x = 5808,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 0 },
            { x = 16, y = -16 },
            { x = -16, y = -16 },
            { x = -16, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 430,
          name = "windmill",
          type = "",
          shape = "polygon",
          x = 6960,
          y = 1376,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = 0 },
            { x = 16, y = -16 },
            { x = -16, y = -16 },
            { x = -16, y = 16 },
            { x = 16, y = 16 },
            { x = 16, y = 0 }
          },
          properties = {}
        }
      }
    }
  }
}
